name: code_play
description: "Aplicativo educacional interativo para ensino de conceitos de codificação digital como ASCII, cores RGB e números binários para alunos do 4º ano."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  url_launcher: ^6.2.3
  carousel_slider: ^5.0.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/matrix_bg.png
    - assets/images/mascote.png
    - assets/sounds/click.mp3